apiVersion: v1
kind: Service
metadata:
  name: ingest-server
  namespace: tenant-a
  labels:
    app: ingest-server
    component: observability
spec:
  type: ClusterIP
  selector:
    app: ingest-server
  ports:
  - name: http
    port: 4318
    targetPort: 4318
    protocol: TCP
